### ISSUE TITLE
Choose a prefix

### ISSUE THREAD

**Issue by redbrain** [redbrain/pvss-v3#1]
What prefix should the bot use? Discuss.

**Comment by redbrain** [comment]
I'd personally go for `/`. It's relatively unused by other bots, as well as classic and easy to type.
As a side perk, it can be neatly stylistically switched to Discord's "slash-commands" once discord.js supports them.

**Comment by MithicSpirit** [comment]
We shouldn't use `/` except for when we start using the slash commands in order to prevent collision with actual slash commands (I presume discord will have some built-in way to prevent/deal with collisions). I think that we should go for `.` since that is currently unused by any other bot on the server.

**Comment by redbrain** [comment]
Noted. Switching to `.`, closing.

**Comment by namatchi** [comment]
`.` is used as a command prefix in some discord clients. `!` would be a better, more ubiquitous prefix to use as a default. We should allow for prefixes to be changed within config files.

**Comment by redbrain** [comment]
`!` is already used by a lot of bots (mee6, carl, rythm, etc), conflicts could arise easily.
The prefix is already configurable in (src/config.def.ts) `config.clientOptions.commandPrefix`.
